services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app:cached
      - /app/node_modules
    working_dir: /app
    environment:
      - HOST=0.0.0.0

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/src

        - action: rebuild
          path: package.json
          target: /app
    working_dir: /app
